name: mooeat frontend deploy
on:
  push:
    branches: ['develop']
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          password: ${{ secrets.REMOTE_SSH_PASSWORD }}
          key: ${{ secrets.REMOTE_SSH_KEY  }}
          port: ${{ secrets.REMOTE_SSH_PORT  }}
          timeout: 40s
          script: |
            whoami
            cd Mooeat
            sudo git pull origin develop
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            npm run build
            if pm2 describe mooeat > /dev/null; then
              pm2 restart mooeat
            else
              pm2 start ecosystem.config.js --env production
            fi
